DELETE http://localhost:3001/api/persons/3

###

DELETE http://localhost:3001/api/persons/17973

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "police",
    "number": 911
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": 911
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Flavie",
    "id":234
}